server:
  port: 0
  forward-headers-strategy: framework
spring:
  application:
    name: main-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
bot:
  telegram:
    token: ${TELEGRAM_BOT_TOKEN}
schedule:
  page_size: 5
base:
    page_size: 20
grpc:
  client:
    schedule-script:
      address: schedule-script-service
      negotiation-type: plaintext