services:
  pgk.eureka-server:
    image: pgk.eureka-server:latest
    build:
      context: eureka-server
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8761:8761"
    env_file: .env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
  pgk.main-service:
    image: pgk.main-service:latest
    build:
      context: main-service
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "18021:8080"
    env_file: .env
  pgk.security-service:
    image: pgk.security-service:latest
    build:
      context: security-service
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "18021:8081"
    env_file: .env
  pgk.teacher-service:
    image: pgk.teacher-service:latest
    build:
      context: teacher-service
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "18021:8082"
    env_file: .env
  pgk.api-gateway:
    image: pgk.api-gateway:latest
    build:
      context: api-gateway
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "10765:10765"