server:
  port: 10765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "https://pgk.admin.danbel.ru:30"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      default-filters:
        - name: AuthFilter
          args:
            routes:
              - name: admin-service
                adminTypes:
                  - FULL
              - name: teacher-service
                methods:
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                adminTypes:
                  - EDUCATION_PART
                  - FULL
grpc:
  client:
    auth:
      address: security-service
      negotiation-type: plaintext
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
