server:
  port: 10025
spring:
  datasource:
    url: jdbc:postgresql://danbel.ru:5432/pgk-schedule
    username: postgres
    password: danbelZzAa6190
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: danbel.ru
      port: 6379
      password: ggtt1234redis