server:
  port: 0
spring:
  application:
    name: main-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
bot:
  telegram:
    token: ${TELEGRAM_BOT_TOKEN}
schedule:
  page_size: 5
  script:
    url: ${SCHEDULE_SCRIPT_BASE_URL}
base:
    page_size: 20