ALTER TABLE admins
DROP COLUMN username,
DROP COLUMN password;

ALTER TABLE users
    ADD COLUMN username VARCHAR(32) UNIQUE DEFAULT NULL,
ADD COLUMN password VARCHAR(64) DEFAULT NULL;

INSERT INTO admin_types (type)
VALUES ('FULL'), ('EDUCATION_PART');
